### ISSUE TITLE
The SEO Framework destroys Relevanssi Search Plugin

### ISSUE THREAD

**Issue by they-are** [sybrew/the-seo-framework#23]
Hi there,

you're doing a great job! Thank you very much for that very useful and clean plugin. Looking forward to see much more in the future like a global settings page for multisite networks. :)

However I found out that it breaks the search results if Relevanssi is activated. I was happy to find the solution in another answer here on GutHub and want to go sure that you're aware of this so other users find the issue solution as well.

Adding
`add_action( 'init', 'seo_remove_search_filter' );
function seo_remove_search_filter() {
	if ( function_exists( 'the_seo_framework' ) )
		remove_action( 'pre_get_posts', array( the_seo_framework(), 'search_filter' ), 999 );
}`
to functions.php let's Relevanssi work as expected. Maybe you can add a check for common search enhancement plugins like Relevanssi.

Best regards,

Philipp

**Comment by sybrew** [comment]
Hi Philipp,

Thank you so much for the kind words!

Could you elaborate on "destorying/breaking" of the search results with perhaps an example? Thanks!

**Comment by sybrew** [comment]
Hi Philipp,

I've just pushed a change to Master: https://github.com/sybrew/the-seo-framework/commit/3478a7de27bd549e71e3b0fccb5abfa01192e2f9

This commit overhauled the search exclusion. Could you please test it out and see if there's still a conflict?

Thanks!

**Comment by sybrew** [comment]
This issue has most likely been fixed in 2.7.0. 

If this is not the case, please let me know and feel free to re-open this issue.

**Comment by S-n-d** [comment]
Hi @sybrew ,

I'm having this exact issue with the most recent version of both plugins. 
Am I missing something?

**Comment by sybrew** [comment]
Hi @S-n-d 

Please see if changing the `General > Performance > Perform alteration` setting from "in the database" to "on the site" works for you.

![image](https://user-images.githubusercontent.com/7662236/69662523-ce3c3080-1084-11ea-8cf8-ffe1e12268f6.png)

If that doesn't work, you may want to disable the search query alteration. Cheers!

**Comment by S-n-d** [comment]
Hi @sybrew 

Thanks for the quick answer! I tried your solution but I still get the same result.

![Screenshot 2019-11-27 at 14 15 40](https://user-images.githubusercontent.com/46485243/69726259-705d2680-1120-11ea-98e9-bf9d175e6b51.png)

As you can see, all posts are being excluded. When I disable the SEO framework plugin it works as intended. I'm using this on a multisite setup, don't know if that makes any difference?

**Comment by sybrew** [comment]
Hi @S-n-d 

I'm afraid I can't reproduce this issue, with or without the settings adjusted of The SEO Framework.

I'm not sure where this issue may be at play. We removed all known query conflicts in the v4.0 update, which is after we already started cleaning up after ourselves ever since v2.7. Your report is the first time we hear from this in three years, so there may be more plugins in the setup that cause interference when combined with TSF. But, I'm unaware of third-party solutions related to (database, permalink) queries that try to enact on TSF.

Could you please relay this information to the Relevanssi support team? They may be aware of known conflicts. I'll gladly look into this with them, but I don't know where to start right now. Thank you!

**Comment by S-n-d** [comment]
Hi @sybrew, thank you very much for your replies and sorry for the late follow-up.
It seems the issue was on my end: I was using staging and dev environments and the permalinks in the database were not corresponding to the right environment.

Again thanks for the help!
